name: Vane_Angular_Todo
dependencies:
  angular: 1.0.0
  browser: '>=0.10.0 <0.11.0'
  http: any
  unittest: '>=0.11.0 <0.12.0'
  uuid: '>=0.3.2 <0.4.0'
  vane: '>=0.6.0 <0.7.0'

transformers:
- angular:
    dart_sdk: "/www/dart-sdk/latest"

